name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore backend backend.Tests
      - name: Build
        run: dotnet build --no-restore backend backend.Tests
      - name: Test
        run: dotnet test --no-build backend.Tests
      - name: Frontend install
        run: |
          cd frontend
          npm ci || npm install
      - name: Frontend build
        run: |
          cd frontend
          npm run build


